// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/Clinical.tsx": () => import("../components/mockups/home-redesign/Clinical.tsx"),
  "./components/mockups/home-redesign/NavyConfident.tsx": () => import("../components/mockups/home-redesign/NavyConfident.tsx"),
  "./components/mockups/home-redesign/WarmApproachable.tsx": () => import("../components/mockups/home-redesign/WarmApproachable.tsx")
};
